import '@/lib/font'
import "@/node_modules/react-modal-video/css/modal-video.css"
import "../public/assets/css/bootstrap.css"
import "../public/assets/css/color.css"
import "../public/assets/css/style.css"
import 'swiper/css'
// import "swiper/css/navigation"
import "swiper/css/pagination"
import 'swiper/css/free-mode';

export const metadata = {
    title: 'Ticrou Template',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="it">
            <body>{children}</body>
        </html>
    )
}
