export const WINES_MENU_TABS = [
  { id: 'bollicine', label: 'Bollicine' },
  { id: 'bianchi', label: 'Bianchi' },
  { id: 'rossi', label: 'Rossi' },
  { id: 'rosati', label: 'Rosati' },
];

export const WINES_PDF_URL = '/assets/menu/vini.pdf';

export const menuWines = [
  {
    id: 'champagne-orban',
    category: 'bollicine',
    name: 'Champagne Brut Reserve Vieilles Vignes',
    producer: 'Francis Orban — Leuvrigny (Champagne / Francia)',
    description: '100% Meunier Noir. Di grande morbidezza, con freschezza persistente e ottimo equilibrio.',
    price: '€ 68,00',
    servingTemp: '4–6 °C',
  },
  {
    id: 'saxanigra',
    category: 'bollicine',
    name: 'Saxanigra Dosaggio Zero Etna Spumante Doc Metodo Classico',
    producer: 'Cantina Destro',
    description: 'Prodotto da uve Nerello Mascalese. Fresco, profondo, elegante, dinamico e di grande armonia.',
    price: '€ 34,00',
    servingTemp: '4–6 °C',
  },
  {
    id: 'murgo-brut',
    category: 'bollicine',
    name: 'Murgo Brut Metodo Classico',
    producer: 'Cantine Murgo',
    description: '100% Nerello Mascalese. Fresco e cremoso, supportato da una decisa mineralità che persiste nel lungo finale.',
    price: '€ 30,00',
    servingTemp: '4–6 °C',
  },
  {
    id: 'valdemone-brut',
    category: 'bollicine',
    name: 'Valdemone Brut',
    producer: 'Cantine Tornatore',
    description:
      'Brut ottenuto da uve di Nerello Mascalese vinificato in bianco con metodo charmat. Sapido, secco e profumato.',
    price: '€ 23,00',
    servingTemp: '4–6 °C',
  },
  {
    id: 'franciacorta-solouva',
    category: 'bollicine',
    name: 'Franciacorta Brut DOCG metodo classico',
    producer: 'SoloUva — Coccaglia (Brescia)',
    description: '100% Chardonnay. Fresco, dinamico e brioso, di piacevole sapidità.',
    price: '€ 39,00',
    servingTemp: '4–6 °C',
  },
  {
    id: 'piante-sparse',
    category: 'bianchi',
    name: 'Piante Sparse Etna Bianco DOC',
    producer: 'Azienda Agricola AYUNTA',
    description:
      'Carricante, Catarratto, Gracanico, Muscatedda. Acido, fresco, complessità e un prorompente corpo minerale.',
    price: '€ 32,00',
    servingTemp: '10–12 °C',
  },
  {
    id: 'etna-bianco-tornatore',
    category: 'bianchi',
    name: 'Etna Bianco Doc',
    producer: 'Tornatore',
    description: '100% Carricante. Sapido, fresco, minerale e dai ritorni aromatici.',
    price: '€ 30,00',
    servingTemp: '8–10 °C',
  },
  {
    id: 'pietrarizzo',
    category: 'bianchi',
    name: 'Pietrarizzo Etna Bianco Doc',
    producer: 'Tornatore',
    description:
      '100% Carricante. Piacevolissima sapidità e freschezza completate da una straordinaria complessità.',
    price: '€ 42,00',
    servingTemp: '8–10 °C',
  },
  {
    id: 'terre-nere-bianco',
    category: 'bianchi',
    name: 'Etna Bianco Doc 2022',
    producer: 'Tenuta delle Terre Nere',
    description: '20% Catarratto, 5% Grecanico, 5% Minnella, 70% Carricante. Elegante e sottile, con un finale sapido.',
    price: '€ 49,00',
    servingTemp: '8–10 °C',
  },
  {
    id: 'sp68-bianco',
    category: 'bianchi',
    name: 'SP68 Bianco IGT Terre Siciliane',
    producer: 'Arianna Occhipinti — Vittoria (Ragusa)',
    description: 'Albanello 50%, Zibibbo 50%. Diretto, dalla nota fresca e quasi erbacea, con un finale asciutto.',
    price: '€ 25,00',
    servingTemp: '8–10 °C',
  },
  {
    id: 'etna-rosato-benanti',
    category: 'rosati',
    name: 'Etna Rosato Doc',
    producer: 'Benanti',
    description: '100% Nerello Mascalese. Fresco e sapido, dalle pronunciate note floreali e fruttate.',
    price: '€ 28,00',
    servingTemp: '10–12 °C',
  },
  {
    id: 'susucaru-rosato',
    category: 'rosati',
    name: 'Susucaru Rosato IGT',
    producer: 'Frank Cornelissen',
    description:
      'Catarratto, Malvasia, Nerello Mascalese. Nota minerale e un finale equilibrato ed omogeneo.',
    price: '€ 28,00',
    servingTemp: '10–12 °C',
  },
  {
    id: 'etna-rosato-tornatore',
    category: 'rosati',
    name: 'Etna Rosato Doc',
    producer: 'Francesco Tornatore',
    description: '100% Nerello Mascalese. Fragranza aromatica e una sapida persistenza gustativa.',
    price: '€ 28,00',
    servingTemp: '10–12 °C',
  },
  {
    id: 'graci-rosato',
    category: 'rosati',
    name: 'Etna Rosato Doc',
    producer: 'Graci',
    description: '100% Nerello Mascalese. Dinamico, armonioso, con note fruttate e piacevole freschezza.',
    price: '€ 33,00',
    servingTemp: '12–14 °C',
  },
  {
    id: 'coti-rosato',
    category: 'rosati',
    name: 'Cotì Rosato Doc',
    producer: 'Masseria del Feudo — Caltanissetta',
    description: '100% Nero d’Avola. Fresco e fruttato, con spiccata vena minerale di grande piacevolezza.',
    price: '€ 22,00',
    servingTemp: '10–12 °C',
  },
  {
    id: 'etna-rosso-tornatore',
    category: 'rossi',
    name: 'Etna Rosso Tornatore Doc',
    producer: 'Francesco Tornatore',
    description: 'Nerello Mascalese, Nerello Cappuccio. Pieno, sapido e succoso, dotato di fitti tannini.',
    price: '€ 29,00',
    servingTemp: '16–18 °C',
  },
  {
    id: 'etna-rosso-statella',
    category: 'rossi',
    name: 'Etna Rosso DOC Biologico',
    producer: 'Azienda Famiglia Statella',
    description:
      '95% Nerello Mascalese, 5% Nerello Cappuccio. Snello ed elegante, con un tannino presente ma vellutato.',
    price: '€ 37,00',
    servingTemp: '16–18 °C',
  },
  {
    id: 'munjebel-rosso',
    category: 'rossi',
    name: 'Munjebel 2022',
    producer: 'Frank Cornelissen',
    description: '100% Nerello Mascalese. Corposo, pieno, di grande impatto, ricco di frutto e di mineralità.',
    price: '€ 59,00',
    servingTemp: '16–18 °C',
  },
  {
    id: 'calderara',
    category: 'rossi',
    name: 'Etna Rosso DOC Calderara',
    producer: 'Francesco Tornatore',
    description:
      'Nerello Mascalese, Nerello Cappuccio. Equilibrato al palato, con tannino dalle note estremamente dolci e setose.',
    price: '€ 75,00',
    servingTemp: '16–18 °C',
  },
  {
    id: 'pistus',
    category: 'rossi',
    name: 'Pistus Etna Rosso',
    producer: 'I Custodi delle Vigne dell’Etna',
    description:
      'Nerello Mascalese 80%, Nerello Cappuccio 20%. Fresco, equilibrato, con buoni tannini ed un piacevole finale fruttato.',
    price: '€ 35,00',
    servingTemp: '16–18 °C',
  },
];

export function getWinesByCategory(category) {
  return menuWines.filter((wine) => wine.category === category);
}
